[package]
name = "dawn_cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "dawn"
path = "src/main.rs"

[dependencies]
dawn = { workspace = true }
